Add required psutil
lock.requirements.txt:
    * psutil is needed

docker logs gc-ml-api
```
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/app-root/src/gamechangerml/api/fastapi/mlapp.py", line 4, in <module>
    from gamechangerml.api.fastapi.routers import startup, search, controls
  File "/opt/app-root/src/gamechangerml/api/fastapi/routers/startup.py", line 28, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
```

Signed-off-by: Tuan T. Pham <tuan.pham@nalej.com>